[package]
name = "svgcleaner"
version = "0.8.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg", "cleaner", "optimizer"]
license = "GPL-2.0"
description = "svgcleaner could help you to clean up yours SVG files from the unnecessary data."
documentation = "https://github.com/RazrFalcon/svgcleaner/blob/master/docs/svgcleaner.rst"
repository = "https://github.com/RazrFalcon/svgcleaner"
readme = "README.md"
categories = ["multimedia::images"]

[badges]
travis-ci = { repository = "https://github.com/RazrFalcon/svgcleaner" }

[dependencies.svgdom]
# latest
git = "https://github.com/RazrFalcon/libsvgdom.git"
# local copy
# path = "../svgdom"
# from crates
# version = "=0.3.0"

[dependencies.clap]
version = "=2.20.0"
default-features = false

# makes it 5-10% faster, but very slow to compile
# use only for main releases
# [profile.release]
# opt-level = 3
# lto = true

[lib]
doctest = false
