[package]
name = "svgcleaner"
version = "0.7.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg", "cleaner", "optimizer"]
license = "GPL-2.0"
description = "svgcleaner could help you to clean up yours SVG files from the unnecessary data."
readme = "README.md"

[dependencies]
# latest
svgdom = { git = "https://github.com/RazrFalcon/libsvgdom.git" }
# local copy
# svgdom = { path = "../svgdom" }
# from crates
# svgdom = "0.0.3"

[dependencies.clap]
version = "2.14"
default-features = false

# makes it 5-10% faster, but very slow to compile
# use only for main releases
[profile.release]
opt-level = 3
lto = true

[lib]
doctest = false
